### ISSUE TITLE
Errors when opening new Homebridge instance with just this plugin installed

### ISSUE THREAD

**Issue by lanceuppercut47** [codetheweb/homebridge-tuya#2]
I had been using the old homebridge-tuya-outlet without issue but couldn't get it working with more than one socket.

Had been pointed towards this one but when running a test Homebridge instance on my Mac with just this plugin loaded, I had to use "sudo npm install -g homebridge-tuya" to install the plugin, seemingly without error.

There is nothing configured for this plugin in the config.json yet, I get this error:

[8/18/2018, 2:50:43 PM] Loaded config.json with 0 accessories and 0 platforms.
[8/18/2018, 2:50:43 PM] ---
**[8/18/2018, 2:50:43 PM] ====================
[8/18/2018, 2:50:43 PM] ERROR LOADING PLUGIN homebridge-tuya:
[8/18/2018, 2:50:43 PM] /usr/local/lib/node_modules/homebridge-tuya/lib/discovery.js:12
  async startDiscovery() {
        ^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya/index.js:1:84)
[8/18/2018, 2:50:43 PM] ====================**
[8/18/2018, 2:50:43 PM] No plugins found. See the README for information on installing plugins.
[8/18/2018, 2:50:43 PM] Loading 0 platforms...
[8/18/2018, 2:50:43 PM] Loading 0 accessories...
Setup Payload:
X-HM://0024ZJIS8LH6L
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                           
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 917-23-992 │     
    └────────────┘     
                       
[8/18/2018, 2:50:43 PM] Homebridge is running on port 64374.

What am I doing wrong?

**Comment by codetheweb** [comment]
Your Node version is too old, you need to update to >= 8.x.x.

**Comment by lanceuppercut47** [comment]
I updated using the commands here:

https://stackoverflow.com/questions/11284634/upgrade-node-js-to-the-latest-version-on-mac-os

but this is what I get:

**Last login: Sat Aug 18 19:00:51 on ttys000
Matts-MacBook-Pro:~ matt$ node -v
v10.8.0
Matts-MacBook-Pro:~ matt$ homebridge
/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)**


I've tried both "npm rebuild" and "npm install" as well as running them as sudo, same errors.

**Comment by codetheweb** [comment]
Try uninstalling and re-installing Homebridge: `npm uninstall homebridge -g && npm install homebridge -g` or `sudo npm uninstall homebridge -g && sudo npm install homebridge -g`.

**Comment by codetheweb** [comment]
👍
