### ISSUE TITLE
Two gang light switch conflict

### ISSUE THREAD

**Issue by sloaiza86** [codetheweb/homebridge-tuya#6]
Two gang light switch added to config.json using dps 1 and 2 with same IDs and keys, but home app only adds one switch (with the name given to dps=1) that when clicked turns on/off dps=1 and 2 seconds later turns on/off dps=2. The following errors are displayed:

> (node:745) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at device.set.then.catch.error (/usr/local/lib/node_modules/homebridge-tuya/lib/generic.js:55:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:745) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

When only one dps (either dps=1 or dps=2) is left in the config.json, it displays the correct name and the correct dps is turned on/off and no errors are displayed.

**Comment by codetheweb** [comment]
I think the issue is that the UUID (unique identifier) used internally by Hombridge is currently generated by the device's ID, which obviously produces a collusion when the same device is provided in `config.json` with different DPS indices.

I'll have to updated the code to use the device ID + the device's name as input for the UUID generator.

#4 is probably related to the same bug.

**Comment by sloaiza86** [comment]
Is this the problematic line?

`const uuid = this.api.hap.uuid.generate(device.id);`

**Comment by codetheweb** [comment]
That's one of them, I think there's a few more.  You should be able to find them all by searching the project for 'generate'. 

Sorry I can't help more right now, I'm on mobile.

**Comment by sloaiza86** [comment]
No need to be sorry. Your contribution to the community is already huge and is enabling a lot of us to deploy low-cost tuya based homekit implementations.

I haven't code like in 15 years, so I don't even know how to compile this code but it seemed like a good chance to remove the dust from the keyboard and read some tutorials.

**Comment by codetheweb** [comment]
Should be fixed now, although I can't currently test it.

**Comment by sloaiza86** [comment]
Great! I will update and test as soon as I get home and let you know! Huge thanks Max.

**Comment by sloaiza86** [comment]
Updated to 0.1.3 and didn’t work, but rolled back to 0.1.2 to try my previous configuration (with one dps only) and didn’t work either, so probably it something in my side. Will do a fresh install and keep you posted.

**Comment by codetheweb** [comment]
Ok.  The other user that was having a similar issue reported that their configuration now works.

**Comment by sloaiza86** [comment]
Max, it works! Flawlessly.
THANK YOU!

**Comment by gonzechevnublit** [comment]
Hello, I have similar issue. can you tell me how to solve it? Best regards
